#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [3]:
import numpy as np

#THE BASICS :

In [4]:
#initialize array
a=np.array([1,2,3],dtype="int16") 

# with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 


In [5]:
print("one dimensional array :",a)

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)


one dimensional array : [1 2 3]
two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


#Get Dimension

In [6]:
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2



#Get Shape

In [7]:
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


In [8]:

#Get  Type
print("a type is :",a.dtype)


a type is : int16


In [7]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [8]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;

In [9]:
b[1,2]

np.float64(4.2)


#Get specific row [row,:]#we use slicing(:) operation

In [10]:
print("row :",b[1,0:1]);

row : [2.1]


In [11]:
#Get specific column[:,column]
print("column :",b[:,1])


column : [2. 3.]


In [12]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [15]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [13]:
print(a)

[1 2 3]


In [14]:
int(1.2)

1

In [17]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [25]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
type(c)

numpy.ndarray

In [27]:
c.ndim

3

In [28]:
c.shape

(2, 2, 2)

In [29]:
c.size

8

Calculate the memory space took for c numpy array

Initilization Diffrent Types  of Arrays

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
zm = np.zeros((3,4))

In [33]:
zm.ndim

2

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#Any others number


In [36]:
np.full((4,5),100, dtype="float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [38]:
np.full_like(zm, 100, dtype="float")

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

Ranom matrix

In [39]:
np.random.randint(1, 10, size=(2,3))

array([[8, 1, 3],
       [1, 8, 3]], dtype=int32)

#generate identity matrix only one argument bcoz identity matrix is a

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])